Repository cs169/berkeley-reentry-student-program, pull requests merged in 2025-04, with the labels that each got.

#72 Added Accessibility Tests and Fixed UI Accordingly
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/views/pages/index.html.erb
  features/accessibility.feature
  features/support/axe_cucumber.rb
  features/support/capybara.rb
Labels: 👀 accessibility

#74 Feature: Load scholarships from databases.
  README.md
  app/controllers/scholarships_controller.rb
  app/helpers/application_helper.rb
  app/models/scholarship.rb
  app/views/admin/scholarships/edit.html.erb
  app/views/admins/index.html.erb
  app/views/scholarships/index.html.erb
  config/routes.rb
  db/migrate/20250406052745_create_scholarships.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/scholarships.rb
  spec/models/scholarship_spec.rb
Labels: 🏗️ infrastructure

#87 Installed Action Text
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/actiontext.css
  app/javascript/application.js
  app/views/active_storage/blobs/_blob.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  config/importmap.rb
  db/migrate/20250411044224_create_active_storage_tables.active_storage.rb
  db/migrate/20250411044225_create_action_text_tables.action_text.rb
  db/schema.rb
Labels: points: 1

#93 Fix navbar to highlight current page
  app/views/shared/_navbar.html.erb
Labels: enhancement
